{"cells":[{"cell_type":"code","execution_count":1,"id":"ff348a42","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ff348a42","executionInfo":{"status":"ok","timestamp":1678502456549,"user_tz":-480,"elapsed":18997,"user":{"displayName":"张俊杰","userId":"00038772554491905462"}},"outputId":"22a4226c-2fff-4d0d-a0ac-16c0d88b9436"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","\n","drive.mount('/content/drive')\n","\n","# TODO: Enter the path in your Drive of the assignment.\n","# e.g. 'cs231n/assignments/assignment1/'\n","FOLDERNAME = 'cs231n/assignments/assignment1/'\n","\n","assert FOLDERNAME is not None, \"[!] Enter the foldername.\""]},{"cell_type":"markdown","id":"88d38cd1","metadata":{"id":"88d38cd1"},"source":["# Collect Submission - Zip + Generate PDF \n","\n","Run this notebook once you have completed all the other notebooks: `knn.ipynb`, `svm.ipynb`, `softmax.ipynb`, `two_layer_net.ipynb` and `features.ipynb`).\n","\n","It will:\n","\n","* Generate a zip file of your code (`.py` and `.ipynb`) called `a1_code_submission.zip`.\n","* Convert all notebooks into a single PDF file called `a1_inline_submission.pdf`.\n","\n","If your submission for this step was successful, you should see the following display message:\n","\n","`### Done! Please submit a1_code_submission.zip and a1_inline_submission.pdf to Gradescope. ###`\n","\n","Make sure to download the zip and pdf file locally to your computer, then submit to Gradescope. Congrats on succesfully completing the assignment!"]},{"cell_type":"code","execution_count":2,"id":"e9aa9ce5","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"e9aa9ce5","executionInfo":{"status":"ok","timestamp":1678502490072,"user_tz":-480,"elapsed":30167,"user":{"displayName":"张俊杰","userId":"00038772554491905462"}},"outputId":"e0a82a5d-bee3-4bad-ad2b-ca071982df44"},"outputs":[{"output_type":"stream","name":"stdout","text":["/content/drive/My Drive\n","/content/drive/My Drive/cs231n/assignments/assignment1\n","Reading package lists... Done\n","Building dependency tree       \n","Reading state information... Done\n","E: Unable to locate package texlive-generic-recommended\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting PyPDF2\n","  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m232.6/232.6 KB\u001b[0m \u001b[31m8.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: typing_extensions>=3.10.0.0 in /usr/local/lib/python3.9/dist-packages (from PyPDF2) (4.5.0)\n","Installing collected packages: PyPDF2\n","Successfully installed PyPDF2-3.0.1\n","### Zipping file ###\n","### Creating PDFs ###\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.9/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF knn.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.9/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF svm.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.9/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF softmax.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.9/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF two_layer_net.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.9/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF features.ipynb.\n","Traceback (most recent call last):\n","  File \"/content/drive/My Drive/cs231n/assignments/assignment1/makepdf.py\", line 45, in <module>\n","    main(args.notebooks, args.pdf_filename)\n","  File \"/content/drive/My Drive/cs231n/assignments/assignment1/makepdf.py\", line 29, in main\n","    merger = PdfFileMerger()\n","  File \"/usr/local/lib/python3.9/dist-packages/PyPDF2/_merger.py\", line 817, in __init__\n","    deprecation_with_replacement(\"PdfFileMerger\", \"PdfMerger\", \"3.0.0\")\n","  File \"/usr/local/lib/python3.9/dist-packages/PyPDF2/_utils.py\", line 369, in deprecation_with_replacement\n","    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))\n","  File \"/usr/local/lib/python3.9/dist-packages/PyPDF2/_utils.py\", line 351, in deprecation\n","    raise DeprecationError(msg)\n","PyPDF2.errors.DeprecationError: PdfFileMerger is deprecated and was removed in PyPDF2 3.0.0. Use PdfMerger instead.\n"]}],"source":["%cd drive/My\\ Drive\n","%cd $FOLDERNAME\n","!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended\n","!pip install PyPDF2\n","!bash collectSubmission.sh"]}],"metadata":{"colab":{"provenance":[]},"language_info":{"name":"python"},"kernelspec":{"name":"python3","display_name":"Python 3"},"gpuClass":"standard"},"nbformat":4,"nbformat_minor":5}